/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.segundoevaluableinterfaces.vista;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author PC220
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    
    // Variables que aún no tienen lugar
    
    private boolean negrita = false; 
    private ImageIcon icon; 
    private StyledEditorKit editor; 
    private MutableAttributeSet attri; 
    private Font font; 
    private String tipo; 
    private final int DEFAULT_SIZE = 12; 
    private int size; 
    private String message; 
    
    public Vista() {
        initComponents();
        
        Size.setValue(DEFAULT_SIZE);
        
        // Declaramos 
        editor  = new StyledEditorKit();
        attri  = editor.getInputAttributes(); 
        font = new Font("Garamond", Font.PLAIN, DEFAULT_SIZE); 
        size = DEFAULT_SIZE; 
        message = ""; 
        
        // Centrar la pantalla 
        this.setLocationRelativeTo(null);
        
        // Cargar un estilo de pantalla "Moderno" 
        try{
            Theme.setIcon(new ImageIcon(getClass().getResource("/Theme/Luna.png")));
            UIManager.setLookAndFeel(new FlatLightLaf());
            FlatLaf.updateUI();
        }catch(Exception e){
            System.err.println("No funciona el cambio de tema!"); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextPane();
        Theme = new javax.swing.JToggleButton();
        Size = new javax.swing.JSpinner();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(Text);

        Theme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThemeMouseClicked(evt);
            }
        });

        Size.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SizeMouseClicked(evt);
            }
        });

        jToggleButton1.setText("Cambiar Tamaño");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jMenu1.setText("Guardar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu7.setText("Cargar");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Nuevo");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu2.setText("Tipo de Letra");

        jMenuItem4.setText("Times New Roma");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Arial");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Garamond");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseClicked(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Negrita");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Color");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Autor/a");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 448, Short.MAX_VALUE)
                        .addComponent(Theme, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Theme, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1))
                        .addGap(16, 16, 16)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThemeMouseClicked
        if(Theme.isSelected()){
            try{
                Theme.setIcon(new ImageIcon(getClass().getResource("/Theme/Sol.png")));
                UIManager.setLookAndFeel(new FlatDarkLaf());
                FlatLaf.updateUI();
            }catch(Exception e){
                
            }
        }else{
            try{
                Theme.setIcon(new ImageIcon(getClass().getResource("/Theme/Luna.png")));
                UIManager.setLookAndFeel(new FlatLightLaf());
                FlatLaf.updateUI();
            }catch(Exception e){
                    
            }
        }
    }//GEN-LAST:event_ThemeMouseClicked

    // Cambio de color a "Negrita" 
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked

        if(negrita){
            this.negrita = false; 
        }else if(!negrita){
            this.negrita = true; 
            StyleConstants.setFontSize(attri, (int) Size.getValue()); 
            StyleConstants.setBold(attri, true);
            Text.setCharacterAttributes(attri, false);
        }
        
    }//GEN-LAST:event_jMenu3MouseClicked

    // Elegir un color 
    
    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        
        JColorChooser color = new JColorChooser(); 
        int resultado = JOptionPane.showConfirmDialog(null, color, "Selecciona un color", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if(resultado == JOptionPane.OK_OPTION){
            Color c = color.getColor(); 
            StyleConstants.setFontSize(attri, (int) Size.getValue()); 
            StyleConstants.setForeground(attri, c);
            Text.setCharacterAttributes(attri, false);
        }
        
    }//GEN-LAST:event_jMenu4MouseClicked

    // Ayuda sobre los controles 
    
    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked

        String message = "Ctrl + N -> Nuevo Archivo "
                + "\nCtrl + O -> Abrir Documento"
                + "\nCtrl + G -> Guardar"; 
        icon = new ImageIcon(getClass().getResource("/Icons/Duda.png")); 
        JOptionPane.showConfirmDialog(null, message, "Controles", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,icon ); 
                
    }//GEN-LAST:event_jMenu5MouseClicked
    
    // Información sobre el autor/a del documento
    
    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        
        String message = "Autor/a -> " + System.getProperty("user.name") 
                + "\nFecha -> " + LocalDate.now(); 
        icon = new ImageIcon(getClass().getResource("/Icons/Toy.png")); 
        JOptionPane.showConfirmDialog(null, message, "Controles", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,icon ); 
        
    }//GEN-LAST:event_jMenu6MouseClicked
    
    // Primer tipo de letra 
    
    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        font = new Font("Times New Roman", Font.PLAIN, 12); 
    }//GEN-LAST:event_jMenuItem4MouseClicked

    // Segundo tipo de letra 
    
    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked
        font = new Font("Times New Roman", Font.PLAIN, 12); 
    }//GEN-LAST:event_jMenuItem5MouseClicked

    // Tercer Tipo de letra 
    
    private void jMenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseClicked
        font = new Font("Times New Roman", Font.PLAIN, 12); 
    }//GEN-LAST:event_jMenuItem6MouseClicked

    
    
    private void SizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SizeMouseClicked
        
    }//GEN-LAST:event_SizeMouseClicked

    // Cambiamos el tamaño de la letra 
    
    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        StyleConstants.setFontSize(attri, (int) Size.getValue()); ;
        Text.setCharacterAttributes(attri, false);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    // Cargar Archivo Existente 
    
    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        this.pruebaArchivo();
    }//GEN-LAST:event_jMenu7MouseClicked

    // Nuevo Archivo 
    
    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
       Text.setText("");
    }//GEN-LAST:event_jMenu8MouseClicked

    // Guardar 
    
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        
        JFileChooser file = new JFileChooser(); 
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resultado = file.showOpenDialog(this); 
        
        if(resultado == JFileChooser.APPROVE_OPTION){
            java.io.File archivo = file.getSelectedFile(); 
            
            File documento = new File(archivo.getAbsolutePath()); 
            try { 
                documento.createNewFile();
                message = Text.getText();
                BufferedWriter bw = new BufferedWriter(new FileWriter(documento.getAbsolutePath()));  
                System.out.println(message);
                bw.write(message);
                bw.close(); 
            } catch (IOException ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        
    }//GEN-LAST:event_jMenu1MouseClicked

    
    
    public void pruebaArchivo(){
        JFileChooser file = new JFileChooser(); 
        int resultado = file.showOpenDialog(this); 
        
        if(resultado == JFileChooser.APPROVE_OPTION){
            java.io.File archivo = file.getSelectedFile(); 
            message = ""; 
            try { 
                BufferedReader bf = new BufferedReader(new FileReader(archivo.getAbsolutePath()));
                String linea; 
                
                while((linea = bf.readLine()) != null){
                    
                    message = message + linea + "\n"; 
                    
                }
                
                Text.setText(message);
                
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Size;
    private javax.swing.JTextPane Text;
    private javax.swing.JToggleButton Theme;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
